project:
  title: "Grupo Energía Eólica"
  output-dir: ./_site/es

website:
  navbar:
    left:
      - href: index.qmd
        text: Principal
      - icon: book
        href: research.qmd
        text: Publicaciones
      - href: services.qmd        
        text: Servicios y Cursos
      - href: study.qmd
        text: Especialista en Eólica
    right:
      - href: ../es
        text: Spanish
      - href: ../en
        text: English

lang: es

format:
  html:
    theme:
        light: ./themes/ier_claro.scss
        dark: ./themes/ier_dark.scss
    css: styles.css
    toc: true