project:
  title: "Grupo Energía Eólica"
  output-dir: ./_site/es

website:
  #google-analytics: "G-JMHP9PPZM4"
  page-navigation: true
  navbar:
    background: primary
    logo: ./imgs/IERBlanco.png
    search: true
    left:
        href: research.qmd
        text: Publicaciones
      - href: services.qmd        
        text: Servicios y Cursos
      - href: career.qmd
        text: Especialista en Eólica
    right:
      - href: ../es
        text: Español
      - href: ../en
        text: English

lang: es

  page-footer: 
    background: primary
    left: "Copyright 2024, Osvaldo Rodríguez. "
    
   
format:
  html:
    toc-title: Contenido
    toc: true
    toc-depth: 4
    theme:
        light: ier_claro.scss
        dark: ier_dark.scss
    css: styles.css
    page-layout: full