---
title: "Servicios y Cursos"
echo: false
section-divs: false
format: html
---

<style>
/* Aplica alineación justificada al texto */
p, h1, h2, h3, h4, h5, h6 {
  text-align: justify;
}
</style>

### Acerca de
El Grupo Energía Eólica es un grupo de reciente creación con líneas de investigación en consolidación; Está compuesto por cinco investigadores, estudiantes de pregrado y posgrado en ingeniería de energías renovables. El grupo tiene experiencia en colaboración internacional con la Universidad de Reading (un proyecto del Fondo Newton), la Universidad de Strathclyde en el Reino Unido y la DTU Delft en los Países Bajos, que aún están activas. Las principales líneas de investigación con equipamiento e instalaciones experimentales se clasifican de la siguiente manera:

### Modelado de evaluación de recursos
Análisis de la modelización meteorológica en aplicaciones eólicas. En esta área, el objetivo principal es evaluar la fiabilidad de los datos de reanálisis y el modelado dinámico para representar las condiciones de la energía eólica, la producción de energía y los factores de capacidad. Los principales retos son entender la variabilidad y complementariedad con los sistemas solares y de almacenamiento en diferentes regiones mexicanas para modelar escenarios de alta penetración de energías renovables de acuerdo con la demanda eléctrica. Además, el pronóstico también es un desafío, y puede basarse en modelos meteorológicos para estimar el pronóstico de 24 horas en consecuencia para el mercado eléctrico mexicano. Por último, aumentar la resolución espacial del modelado dinámico para estudiar la interacción entre las estelas de los aerogeneradores en los conjuntos de parques eólicos o las interacciones de los pequeños aerogeneradores con el medio ambiente. 

### Dinámica de fluidos computacional
El grupo desarrolla códigos numéricos para resolver ecuaciones de conservación de masa y momento de flujo turbulento. Consideramos la formulación de Reynolds Averaged Navier-Stokes (RANS) y exploramos varias alternativas para especificar las condiciones de contorno y el problema de cierre. Recientemente, hemos considerado desarrollar modelos de interacciones fluido-estructura para comprender la transferencia de energía mecánica del viento a un sistema que modifica su posición debido a la interacción aerodinámica. En nuestro contexto, la aplicación obvia de estas condiciones físicas es la interacción del viento con las palas de las turbinas. Además, estamos interesados en la posibilidad de utilizar herramientas de inteligencia artificial para resolver el problema de cierre en turbulencias, y otras herramientas de aprendizaje automático para controlar la dinámica de los aerogeneradores.

### Aerodinámica experimental
El grupo ha diseñado y construido recientemente un pequeño túnel de viento con pequeños ventiladores modulares, controlados individualmente, que impulsan el flujo a través de la sección de trabajo. Se espera que el perfil de velocidad media en el tiempo y el nivel de turbulencia puedan controlarse para imitar, al menos parcialmente, la dinámica de la capa límite atmosférica. El objetivo es probar el rendimiento de turbinas eólicas a escala en condiciones similares a las de la atmósfera terrestre. Se espera que las observaciones en el túnel de viento proporcionen información experimental para verificar los modelos numéricos. 

### Ciencia de datos
Se aplican métodos de Inteligencia Artificial para analizar problemas relacionados con la dinámica del viento, la generación de energía y la generación distribuida, a partir de conjuntos de datos: Métodos de agrupamiento para clasificar los estados del viento en sitios; teoría de redes y aprendizaje automático para la evaluación multiescala de estados eólicos regionales y nacionales;  Redes neuronales para pronosticar la generación de energía y la demanda de electricidad para integrar microrredes inteligentes.

### Electrónica de potencia
El modelado, análisis, diseño, simulación e implementación de dispositivos electrónicos de potencia, se aplican en el acondicionamiento energético para la integración de aerogeneradores en las redes eléctricas, generando un sistema de conversión de energía. Prototipos experimentales a baja escala validan la funcionalidad y robustez de los sistemas de conversión de energía. Se reflejan las características técnicas de los sistemas de ensayo, cuyo análisis se realiza en tiempo real utilizando el simulador de OPAL-RT Technologies®, banco de pruebas para aerogeneradores, dispositivos de electrónica de potencia y un emulador de red eléctrica. 

### Integración de aerogeneradores en redes eléctricas
Análisis de los problemas inherentes a la integración de numerosos aerogeneradores en redes eléctricas y gestión de su contribución (regulación de tensión y frecuencia, operación de parques eólicos, etc.) para garantizar la sostenibilidad y seguridad del suministro. Además, se abordan los desafíos técnicos asociados con la integración de la energía eólica en los sistemas de energía. Estos desafíos incluyen los efectos de la energía eólica en el sistema eléctrico, el costo operativo, la calidad de la energía y los desequilibrios de energía (estabilidad de la red). Por último, se presentan soluciones para mejorar la gestión de la generación eólica y aumentar su penetración en el conjunto de la producción eléctrica.