<style>
/* Justificar el texto de los párrafos y títulos */
p, h1, h2, h3, h4, h5, h6 {
  text-align: justify;
}
</style>

::: {.content-visible when-profile="spanish"}

## Talleres y Servicios
Utilizar fuentes renovables de energía ha generado la necesidad, tanto de instituciones gubernamentales como privadas, de conocer los grandes beneficios de esta tecnología, así como los conceptos técnicos básicos para determinar sus potencialidades y viabilidades. En el IER contribuimos en la formación de recursos humanos especializados en el tema y proveemos soluciones en éste sentido. En este contexto, el Grupo de Energía Eólica del Instituto de Energías Renovables de la UNAM ofrece los siguientes servicios:

### Cursos en Energía Eólica - Unidad de Educación Contínua

<details>
<summary>Energía Eólica para todos</summary>

#### Nombre del curso:

Energía Eólica

Responsables del curso:

- [Dr. Osvaldo Rodríguez Hernández](mailto:osroh@ier.unam.mx) 

#### Objetivo General

Al termino del curso, se habrán abordado los conceptos técnicos fundamentales para relacionados con la Energía Eólica.

#### Objetivos Particulares

- Conocer el contexto nacional y mundial de la Energía Eólica.
- Identificar la metodología y requerimientos básicos para el desarrollo de proyectos eólicos.
- Conocer los sub-sistemas de un así como  los principios mecánicos y aerodinámicos básicos de un aerogenerador.
- Conocer las principales estrategias de integración a la red eléctrica.

#### Temario
1. Antecedentes de la Energía Eólica
2. Conceptos básicos para la evaluación tecno-económica de un proyecto eólico.
3. Principios básicos de extracción de energía del viento. 
4. Principios técnicos básicos de los componentes mecánicos y aerodinámicos de los aerogeneradores.
5. Principios básicos para la integración a  la red de los sistemas eólicos.

A quién va dirigido: Dirigido a profesionistas,  ejecutivos y tomadores de decisión interesados en los aspectos técnicos fundamentales en energía eólica.

**Horas del curso:** de 20 a 40 horas.

**Numero de participantes:** Flexible y adecuado a las necesidades del solicitante.

**Material que incluye:** Material complementario de curso.

Mayores Informes en la Secretaría de Educación Continua al correo: [uec@ier.unam.mx](mailto:uec@ier.unam.mx)

Al término del curso se entregarán constancias de participación.

</details>


<details>
<summary> Modelos meteorológicos para la evaluación del recurso eólico usando Python</summary>

Aquí va el texto que estará oculto hasta que el usuario haga clic en el título desplegable.

Puedes incluir todo tipo de contenido, como texto, imágenes, tablas, etc.

</details>

### Servicios
Ante la gran oferta de servicios eólicos en el mercado, en el IER-UNAM ofrecemos consultorías técnicas en los siguientes tópicos:

- Factibilidad técnica del sitio para el aprovechamiento eólico.
- Asesorías en el desarrollo de campañas de medición.
- Asesoría en la selección de tecnologías para el sitio.
- Comparación y evaluación de propuestas.
- Análisis de integración a la red eléctrica.
- Diseño de sistemas de conversión de energía basados en electrónica de potencia, con aplicaciones específicas en fuentes renovables.
- Consultoría en la supervisión del proyecto.

:::

::: {.content-visible when-profile="english"}

## Workshops and Services
Using renewable energy sources has generated the need, both for governmental and private institutions, to know the great benefits of this technology, as well as the basic technical concepts to determine its potential and viability. At the IER we contribute to the training of human resources specialized in the subject and we provide solutions in this regard. In this context, the Wind Energy Group of the UNAM Renewable Energy Institute offers the following services:

### Courses in Wind Energy - Unidad de Educación Contínua

<details>
<summary>Energía Eólica para todos</summary>

#### Course name:

Energía Eólica

Course leaders:

- [PhD. Osvaldo Rodríguez Hernández](mailto:osroh@ier.unam.mx) 

#### General Objective

At the end of the course, the fundamental technical concepts related to Wind Energy will have been addressed.

#### Specific Objectives

- To understand the national and global context of Wind Energy.
- To identify the methodology and basic requirements for the development of wind projects.
- To understand the sub-systems as well as the basic mechanical and aerodynamic principles of a wind turbine.
- To understand the main strategies for integration into the electrical grid.

#### Syllabus
1. Background of Wind Energy
2. Basic concepts for the techno-economic evaluation of a wind energy project.
3. Basic principles of wind energy extraction.
4. Basic technical principles of the mechanical and aerodynamic components of wind turbines.
5. Basic principles for the integration of wind systems into the grid.

Who is it aimed at: Aimed at professionals, executives and decision makers interested in the fundamental technical aspects of wind energy.

**Course hours:** from 20 to 40 hours.

**Number of participants:** Flexible and adapted to the needs of the applicant.

**Material included:** Supplementary course material.

For more information, please contact the Secretaría de Educación Continua at: [uec@ier.unam.mx](mailto:uec@ier.unam.mx)

At the end of the course, certificates of participation will be issued.

</details>


<details>
<summary> Meteorological models for wind resource assessment using Python</summary>

This is where text will be hidden until the user clicks on the dropdown title.

You can include all kinds of content, such as text, images, tables, etc.

</details>

### Services
Given the wide range of wind services on the market, at IER-UNAM we offer technical consultancy on the following topics:

- Technical feasibility of the site for wind power.
- Consulting on the development of measurement campaigns.
- Consulting on the selection of technologies for the site.
- Comparison and evaluation of proposals.
- Analysis of integration into the electrical grid.
- Design of energy conversion systems based on power electronics, with specific applications in renewable sources.
- Consulting on project supervision.

:::